### ISSUE TITLE
로그인 안해도 userinfo 창 보인다

### ISSUE THREAD

**Issue by muf** [muf/KHU-2017-2-DesignD#29]
## 임시로 해둔 것? or 처리 안 된 부분?
- 버그인듯.. 로그아웃에 refresh가 없어서 생기는 문제

**Comment by Phigaro** [comment]
그거 인지하고있고, 아직 처리 안된 부분 나중에 수정할 예정

**Comment by Phigaro** [comment]
해결 완료

**Comment by muf** [comment]
ㄴㄴ 라벨 떼는게 아니라 그냥 클로즈 하면됨
