### ISSUE TITLE
어플리케이션 내 정적 멤버 cookie userType 변경 요청

### ISSUE THREAD

**Issue by Phigaro** [muf/KHU-2017-2-DesignD#33]
현재 cookie.userType 을

userType
("manager" , "client")

ClinetType
("player", "club") 으로 변경하거나, 더 나은 모델링을 할 필요가 있음

**Comment by muf** [comment]
## 수정
- tpye와 계정의 계층 레벨은 그대로 유지하고, `clientType`을 `LocalData` class의 속성으로 추가하였음.
- 이 경우 최종 자식의 타입을 알수 없어서 기존에 타입을 알고 객체를 만들어서 반환시켜주는 `Retrieve[XXX]Data([XXX])`를 사용하는 것이 불가함.
- 따라서 `getAccountData`를 추가해서 자동으로 최종 자식 타입을 찾아주는 함수를 만들었음.
- 기존 코드 사용하던 부분은 그대로 사용하되, uid로 사용자를 처음부터 알아내야 하는 경우에는 이 함수를 사용하면 됨.

**Comment by muf** [comment]
## 수정
- 기존 clientType 을 type으로 묶어서 표현
- 버그 수정
