### ISSUE TITLE
retrieve 관련 함수 버그 제보

### ISSUE THREAD

**Issue by Phigaro** [muf/KHU-2017-2-DesignD#35]
[user_info.xaml.cs 에서]
public User retrieveUserData(int uid) 함수가 제대로 작동하지 않음.

- 1번 인덱스를 제외한 다른 인덱스 접근 시 잘못된 데이터를 가져옴.

- 테스트 환경은 관리자 로그인 상태에서 인증 여부를 바꿀 때 발생하였음.

**Comment by muf** [comment]
## 버그 수정
- 사유 : 복사 붙여넣기 후 수정 과정 중 수정 미달
`saDAC.getUserData();` -> `saDAC.getUserData(uid);`
```
        public User retrieveUserData(int uid)
        {
            JSON result = saDAC.getUserData(uid);
            if (result.Count > 0) {
                Dictionary<string, object> data = result[0];
         ....

         }

```
## 수정 완료
- commit  4671a77
